# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
- job: ubuntuLatestBuild
  displayName: Ubuntu Latest Build
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: CmdLine@2
    displayName: Install Node Modules
    inputs:
      script: 'npm install'
  - task: CmdLine@2
    displayName: Pack application
    inputs:
      script: 'npm run pack:linux'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: './dist/linux-unpacked/'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-linux.zip'
      replaceExistingArchive: true
  # publish artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Linux Build ($(Build.BuildId))'
      publishLocation: 'Container'
- job: windowsLatestBuild
  displayName: Windows Latest Build
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: CmdLine@2
    displayName: Install Node Modules
    inputs:
      script: 'npm install'
  - task: CmdLine@2
    displayName: Pack application
    inputs:
      script: 'npm run pack:windows'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: './dist/windows-unpacked/'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-windows.zip'
      replaceExistingArchive: true
  # publish artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Windows Build ($(Build.BuildId))'
      publishLocation: 'Container'